services:
  web-ri:
    build: .
    ports:
      - 5300:3000
    environment:
      SDK_RI_ENDPOINT:
      MONGO_URL:
      OIDC_URL:
      VC_URL:
      MARKET_NAME:
  mongo:
    image: mongo:4.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: webri_mongo_user
      MONGO_INITDB_ROOT_PASSWORD: webri_mongo_pass
    ports:
      - 27017:27017
