services:
  app:
    build: .
    ports:
      - 3000:3000
    environment:
      PORT: 3000
  mongo:
    image: mongo:4.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: webri_mongo_user
      MONGO_INITDB_ROOT_PASSWORD: webri_mongo_pass
