services:
  web-ri:
    build: .
    ports:
      - 3000:3000
    environment:
      SDK_RI_ENDPOINT:
      MONGO_URL:
  mongo:
    image: mongo:4.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
    ports:
      - 27017:27017
