services:
  web-ri:
    build: .
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      SDK_RI_ENDPOINT: http://95.211.3.249:8181
      MONGO_URL: mongodb://webri_mongo_user:webri_mongo_pass@mongo:27017/
  mongo:
    image: mongo:4.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: webri_mongo_user
      MONGO_INITDB_ROOT_PASSWORD: webri_mongo_pass
    ports:
      - 27017:27017
